### ISSUE TITLE
showView

### ISSUE THREAD

**Issue by qiuyan81** [LoongerTao/TLTransitions#10]
TLTransitions showView 方法的自动弹起键盘，如果输入框在很高的位置，键盘弹出会在页面最下方，会导致输入框的y=负数。导致看不到输入框，这个问题能解决吗？

**Comment by LoongerTao** [comment]
这个就需要取消键盘自适应功能啦，然后自己适配键盘

**Comment by LoongerTao** [comment]
里面有属性关闭这个功能的，也可以通过自定义动画，这样就可以很大程度DIY了

**Comment by qiuyan81** [comment]
好吧！
