### ISSUE TITLE
请增加一个dismiss完成的回调。。

### ISSUE THREAD

**Issue by qiuyan81** [LoongerTao/TLTransitions#11]
在代码多层嵌套的时候，需要在dismiss后才能push到新的页面，这时就要在dismiss完成后才能进行。。
- (void)dismiss;
- (void)dismissWithCompletion: (void (^ __nullable)(void))completion NS_AVAILABLE_IOS(5_0);

**Comment by qiuyan81** [comment]
- (void)dismissWithCompletion: (void (^ __nullable)(void))completion NS_AVAILABLE_IOS(5_0) {
    [self.presentedViewController dismissViewControllerAnimated:YES completion:completion];
}

**Comment by LoongerTao** [comment]
好，我回去后看看。

**Comment by LoongerTao** [comment]
已经加入dismiss回调
