### ISSUE TITLE
不知道如何使用

### ISSUE THREAD

**Issue by xiaochuiyan** [LoongerTao/TLTransitions#2]
导入头文件#import "TLTransitions.h"  后,使用你说的一步到位的代码 ,根本实现不了功能啊, 迫切的希望 把使用说明写的详细一点,已给星星,望回复,功能强大,但是不知道如何使用,建议demo 写简单一些

**Comment by LoongerTao** [comment]
你需要实现什么功能

**Comment by xiaochuiyan** [comment]
就想实现个转场动画,push 时翻转效果,  返回时也翻转    


我导入了头文件#import “TLTransitions.h”,  然后调用 [self pushViewController:vc swipeType:TLSwipeTypeInAndOut pushDirection:TLDirectionToLeft popDirection:TLDirectionToRight];  push新的控制器啊,好像不行啊 




| |
乜小兵
|
|
nxb168@163.com
|
签名由网易邮箱大师定制


在2018年11月28日 09:36，LoongerTao<notifications@github.com> 写道：

你需要实现什么功能

**Comment by LoongerTao** [comment]
一点效果也没有吗？

**Comment by xiaochuiyan** [comment]
跳转崩溃,我QQ 545222193        加上我给你截图吧,真的麻烦你了




| |
乜小兵
|
|
nxb168@163.com
|
签名由网易邮箱大师定制


在2018年11月28日 09:39，乜小兵<nxb168@163.com> 写道：


就想实现个转场动画,push 时翻转效果,  返回时也翻转    


我导入了头文件#import “TLTransitions.h”,  然后调用 [self pushViewController:vc swipeType:TLSwipeTypeInAndOut pushDirection:TLDirectionToLeft popDirection:TLDirectionToRight];  push新的控制器啊,好像不行啊 




| |
乜小兵
|
|
nxb168@163.com
|
签名由网易邮箱大师定制


在2018年11月28日 09:36，LoongerTao<notifications@github.com> 写道：

你需要实现什么功能

**Comment by LoongerTao** [comment]
swipeType 这个不是翻转类型，是移动类型

**Comment by LoongerTao** [comment]
问题已解决
