### ISSUE TITLE
pod不了啊，找不到文件。

### ISSUE THREAD

**Issue by ThisFriend** [LoongerTao/TLTransitions#3]
pod 'TLTransitions', '~> 1.4.1'   使用这个
直接报错  [!] Unable to find a specification for `TLTransitions (~> 1.4.1)`
使用1.4.0 也是。

**Comment by LoongerTao** [comment]
我上午还pod了，可以的啊

**Comment by LoongerTao** [comment]
platform:ios,'8.0'
target "TestDemo" do
pod "TLTransitions", "~> 1.4.1"
end

**Comment by ThisFriend** [comment]
是啊，我一二十个pod的，就你这个报错  ┑(￣Д ￣)┍

**Comment by LoongerTao** [comment]
刚才试了可以的啊，pod是不是需要清理下缓存

**Comment by ThisFriend** [comment]
我更新升级一下cocoapods试试

**Comment by LoongerTao** [comment]
pod search "TLTransitions" 看看能搜索到不，如果search不到。就是你pod需要，处理一下，我以前遇到过这种情况。好像就是清缓存、更新之类的处理

**Comment by LoongerTao** [comment]
点错按钮关闭了

**Comment by ThisFriend** [comment]
搜不到，所以正在处理。不是你的问题。

**Comment by LoongerTao** [comment]
1. pod repo update

**Comment by LoongerTao** [comment]
这可能是本地的CocoaPods仓库列表没有更新导致的。
1 . 运行以下命令更新本地的CocoaPods仓库列表： 
```pod repo update ```
2. 然后通过以下命令查询
 ```pod search```
3. 如果仍然查询不到最新版本，可以删除本地仓库重新安装。
```sudo rm -rf ~/.cocoapods/repos/master pod setup```
