### ISSUE TITLE
demo初始化错误

### ISSUE THREAD

**Issue by Brances** [LoongerTao/TLTransitions#5]
![image](https://user-images.githubusercontent.com/10275640/49205050-c487da80-f3e8-11e8-8c72-3438716d73f8.png)

**Comment by LoongerTao** [comment]
CATransitionSubtype 是系统类型 ，属于<QuartzCore>，你导入一下看看

**Comment by LoongerTao** [comment]
QuartzCore的内容

**Comment by Brances** [comment]
导入了这个框架 好像还是没找到这个类型

**Comment by LoongerTao** [comment]
<img width="396" alt="image" src="https://user-images.githubusercontent.com/17703615/49206047-bedfc400-f3eb-11e8-91d6-b336c0b295cd.png">

**Comment by Brances** [comment]
我添加了，  是不是没有升级xcode 的原因 我的是9.2

**Comment by LoongerTao** [comment]
不应该吧，这是很早就有的框架了

**Comment by LoongerTao** [comment]
搜索Quartz看看

**Comment by Brances** [comment]
![image](https://user-images.githubusercontent.com/10275640/49206470-25191680-f3ed-11e8-9134-2d3d74e3f060.png)
我已经导进来了，其它类型kCATransitionFromLeft可以搜索到

**Comment by LoongerTao** [comment]
那能编译通过了吗？

**Comment by Brances** [comment]
不能 😢

**Comment by LoongerTao** [comment]
还是那个错误吗？ 这些都是老API了，不应该报错的啊

**Comment by Brances** [comment]
确实很奇怪

**Comment by LoongerTao** [comment]
方便把你的demo发我看看吗

**Comment by Brances** [comment]
可以  邮箱留一下

**Comment by LoongerTao** [comment]
495285195@qq.com

**Comment by Brances** [comment]
已发送至邮箱，请查收

**Comment by LoongerTao** [comment]
ok

**Comment by LoongerTao** [comment]
我这里是正常的，可能和Xcode版本有关系。

**Comment by Brances** [comment]
好的~ 谢谢

**Comment by LoongerTao** [comment]
XCode 9.2 报错问题已经解决，已经将报错字段进行包装屏蔽处理！您如果还有需求可以下载试试看。

**Comment by Brances** [comment]
谢谢  已经可以了
