### ISSUE TITLE
由于dealloc造成的问题，放在这里只是记录一下，方便寻找。

### ISSUE THREAD

**Issue by ThisFriend** [LoongerTao/TLTransitions#6]
#import "UIViewController+Transitioning.h"

// 代码
+ (void)load {
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        Class cls = [UIViewController class];
        Method method1 = class_getInstanceMethod(cls, NSSelectorFromString(@"dealloc"));
        Method method2 = class_getInstanceMethod(cls, @selector(tl_dealloc));
        method_exchangeImplementations(method1, method2);
    });
}

- (void)tl_dealloc{
    
    tl_Log(@"%@ %s", [self class], __func__);
    
    [TLTransitionDelegate removeAnimatorForKey:self];
    
    [self tl_dealloc];
}

**Comment by LoongerTao** [comment]
V 1.4.4 已经解决
