### ISSUE TITLE
作者大神，目前pod直接更新只能update到1.4.1

### ISSUE THREAD

**Issue by happying** [LoongerTao/TLTransitions#7]
作者大神，目前pod直接更新只能update到1.4.1，然而1.4.1上存在pop时的crash

**Comment by LoongerTao** [comment]
这可能是本地的CocoaPods仓库列表没有更新导致的。
1 . 运行以下命令更新本地的CocoaPods仓库列表：
`pod repo update `
2. 然后通过以下命令查询
`pod search`
3. 如果仍然查询不到最新版本，可以删除本地仓库重新安装。
`sudo rm -rf ~/.cocoapods/repos/master pod setup`

**Comment by happying** [comment]
问题解决~果然是因为内外网的原因，要先repo update（另一个影响因素是开了代理），然后就成功了。

**Comment by happying** [comment]
顺便跟作者大大提个意见。就是关于底部tabbar对动画的影响，比如我push 一个页面从底部往上，但是此时底部tabbar是水平移动的隐藏动画效果，导致非常奇怪，另外，如果新controller自带底栏的话，处理起来也有点问题，我目前是用了类似这样的黑魔法来处理的：
￼
![image](https://user-images.githubusercontent.com/7139165/49574092-89525200-f97a-11e8-8f2a-5bc1ee1596ca.png)
作者大大是不是可以考虑真对这块提供一下更有效的的方法？

**Comment by LoongerTao** [comment]
能提供一个demo吗，或者视频，我看下具体情况

**Comment by happying** [comment]
sorry，复现情况比较复杂，复现困难，所以回复慢了，我刚刚重新写了一个demo，发现这种应该是属于特殊情况操作才会出现（tabbar中的controller本身含有一个单独的navigationController时才会出现），理论上这种情况属于特殊情况，不用控件特殊处理。
不过为了后边可能出现类似情况的同学能明白原因，我大致讲一讲问题现场：

![1544094212407](https://user-images.githubusercontent.com/7139165/49580335-a93d4200-f989-11e8-9a8c-4b47be314a26.jpg)

然后在这种状况下，底部tabbar在动画切换时，会出现动画异常：

![qq_20181206191158](https://user-images.githubusercontent.com/7139165/49581282-6a5cbb80-f98c-11e8-9349-18393aed0c08.gif)

解决方案，自行获取最底层的nav进行push即可。

**Comment by LoongerTao** [comment]
我知道了，我会抽时间看看。之前没考虑过这种情况。

**Comment by happying** [comment]
给作者大大点赞，问题我先关了~

**Comment by qiuyan81** [comment]
怎么使用圆形扩散？

**Comment by LoongerTao** [comment]
你可以看看demo，使用TLAnimator中的TLAnimatorTypeCircular类型动画，设置好相关属性startRadius、center（初始半径、圆心坐标）
