### ISSUE TITLE
A push B时有动画， B pop回A时没有动画

### ISSUE THREAD

**Issue by xuuhan** [LoongerTao/TLTransitions#8]

**Comment by xuuhan** [comment]
TLCATransitonAnimator *animator = [TLCATransitonAnimator animatorWithTransitionType:TLTransitionRippleEffect
                                                           direction:TLDirectionToLeft
                                             transitionTypeOfDismiss:TLTransitionRippleEffect
                                                  directionOfDismiss:TLDirectionToRight];
        
        animator.transitionDuration = 0.5;
        [self pushViewController:search animator:animator];
请问是哪里设置错了吗

**Comment by LoongerTao** [comment]
可能和你使用的场景有关系，你目前是什么应用场景？

**Comment by LoongerTao** [comment]
从代码来看你的使用时没有问题的。可能我是我的组件还存在什么BUG，如果方便的话希望可以提供一个简单的demo给我。

**Comment by xuuhan** [comment]
加你qq了😂
