### ISSUE TITLE
Assets图片资源

### ISSUE THREAD

**Issue by SHRemover** [LoongerTao/TLTransitions#9]
效果很炫，只是Assets里面的图片资源太大了，由于个人网速原因，下载Demo体验的时候，下了好久、建议换些小点的😂

**Comment by SHRemover** [comment]
从 popView present 到新页面，还有dismiss返回的时候，popView 的圆角效果会切换一下【圆角效果消失-有圆角】
![qq20190119-101130](https://user-images.githubusercontent.com/16558606/51420974-bc6f3e80-1bd2-11e9-9f10-b2fbf3746951.gif)

**Comment by LoongerTao** [comment]
popover属于弹窗类型，正常的应用场景是不会在弹窗的基础上面再push或者present的。如果有这特殊需求就应该使用自定义控制器转场了。

**Comment by LoongerTao** [comment]
图中的圆角消失是因为present 的tovc覆盖在popover（fromvc）上面把圆角遮盖住了。
